#%RAML 0.8

title: Taxonomy
description: The Taxonomy API provides methods to call all browse tree information destinguished by a unique Jet Node ID.  Additionally this API provides the ability to retrieve variant information for each Jet Node ID.
baseUri: http://merchant-api.test.jet.com/api
version: v0.1
protocols: [HTTPS]
mediaType: application/json

/taxonomy:
    /links:
        /{version}:
            get:
                description: This method retrieves the URLs to all Jet Nodes that are currently active in the Jet.com browse tree
                responses:
                    200:
                        body:
                            application/json:
                                schema: !include taxonomy-links.schema.json
                                example: !include taxonomy-links.example.json
                    404:
                    409:
    /nodes:
        get:
            description: This method retrieves the details for each Jet Node ID
            responses:
                200:
                    body:
                        application/json:
                            schema: !include taxonomy-nodeAttributes.schema.json
                            example: !include taxonomy-nodeAttributes.example.json
                404:
                409:
        /{id}:
            /attributes:
            get:
                description: This method retrieves all the variants and attribute information for a Jet Node ID 
                responses:
                    200:
                        body:
                            application/json:
                                schema: !include taxonomy-nodeAttributes.schema.json
                                example: !include taxonomy-nodeAttributes.example.json
                    404:
                    409: