#%RAML 0.8

title: Merchant API - Orders
description: This API provides actions required for processing orders.
baseUri: http://dev-ironman-webapi.local.jet.com/api
version: v0.1
protocols: [HTTPS]
mediaType: application/json

/orders:
    /withShipmentDetail:
        queryParameters:
            merchantId:
                Merchant Id provided by Jet
        description: This method will list all orders that have not been acknowledged
        get:
            responses:
                200:
                    body:
                        application/json:
                            schema: !include order.schema.json
                            example: !include order.example.json
                404:
    /withNoShipmentDetail:
        queryParameters:
            merchantId:
                Merchant Id provided by Jet
        description: This method will list all orders that have not been acknowledged
        get:
            responses:
                200:
                    body:
                        application/json:
                            schema: !include orderOnly.schema.json
                            example: !include orderOnly.example.json
                404:
    /{id}:
        /accept:
            description: Marks an order as accepted
            post:
                body:
                    application/json:
                        schema: !include order-accept.schema.json
                responses:
                    200:
                    404:
                    409:
        /reject:
            description: Marks an order as rejected (i.e. you will not be fulfilling this order)
            post:
                body:
                    application/json:
                        schema: !include order-reject.schema.json
                responses:
                    200:
                    404:
                    409:
        /shipped:
            description: Marks an order as shipped and provides tracking information to Jet
            post:
                body:
                    application/json:
                        schema: !include order-shipped.schema.json
                responses:
                    200:
                    404:
                    409:
    /refund:
        post:

    /partial-cancel:
        post:

    /returns:
        get:
