#%RAML 0.8

title: Seller API - Orders
baseUri: http://seller..com/api/{version}/seller/{sellerId}
version: v0.1
protocols: [HTTPS]

/orders:
    displayName: Orders
    get:
        responses:
            200:
                body:
                    application/json:
                        schema: !include order.schema.json
                        example: !include order.example.json
/{id}:
    get:

    /accept:
        post:
            body:
                application/json:
                    schema: !include order-accept.schema.json

            responses:
                200:
                404:
                409:

    /reject:
        post:
            body:
                application/json:
                    schema: !include order-reject.schema.json

            responses:
                200:
                404:
                409:


    /shipped:
        post:
            body:
                application/json:
                    schema: !include order-shipped.schema.json

            responses:
                200:
                404:
                409:


/refund:
    post:

/PartialCancel:
    post:

/returns:
    get:
