#%RAML 0.8

title: Seller API - Merchant Skus
baseUri: http://dev-ironman-webapi.local.jet.com/api
version: v0.1
protocols: [HTTPS]
mediaType: application/json

/merchant-skus:
    get:
        queryParameters:
            merchantId:
                description: Merchant Id provided by Jet
        description: This method will list all merchant SKUs
        responses:
            200:
                description: List of all merchant SKUs
                body:
                    application/json:
                        schema: !include merchant-skus.schema.json
                        example: !include merchant-skus.example.json
            404:
    /{id}:
        get:
            queryParameters:
                merchantId:
                    description: Merchant Id provided by Jet
            description: This method will list the specified merchant SKU
            responses:
                200:
                    body:
                        application/json:
                            schema: !include merchant-skus.schema.json
                            example: !include merchant-skus.example.json
                404:
        /inventory:
            put:
                queryParameters:
                    merchantId:
                        description: Merchant Id provided by Jet
                description: This method updates inventory data for the specified merchant SKU
                body:
                    application/json:
                        schema: !include inventory.schema.json
                        example: !include inventory.example.json
                responses:
                   201:
                   204:
                   400:
                   409:
            /{fcid}:
                put:
                    queryParameters:
                        merchantId:
                            description: Merchant Id provided by Jet
                    description: This method updates FC-level inventory data for the specified merchant SKU
                    body:
                        application/json:
                            schema: !include inventory.schema.json
                            example: !include inventory.example.json
                    responses:
                       201:
                       204:
                       400:
                       409:
        /price:
            put:
                queryParameters:
                        merchantId:
                            description: Merchant Id provided by Jet
                description: This method updates price data for the specified merchant SKU
                body:
                    application/json:
                        schema: !include price.schema.json
                        example: !include price.example.json
                responses:
                   201:
                   204:
                   400:
                   409:
            /{fcid}:
                put:
                    queryParameters:
                        merchantId:
                            description: Merchant Id provided by Jet
                    description: This method updates FC-level price data for the specified merchant SKU
                    body:
                        application/json:
                            schema: !include price.schema.json
                            example: !include price.example.json
                    responses:
                        201:
                        204:
                        400:
                        409:
        /image:
            /main:
                put:
                    queryParameters:
                        merchantId:
                            description: Merchant Id provided by Jet
                    description: This method updates the main image for the specified merchant SKU
                    body:
                        application/json:
                            schema: !include image.schema.json
                            example: !include image.example.json
                    responses:
                        201:
                        204:
                        400:
                        409:
            /alternate:
                put:
                    queryParameters:
                        merchantId:
                            description: Merchant Id provided by Jet
                    description: This method updates alternate image data for the specified merchant SKU
                    body:
                        application/json:
                            schema: !include image.schema.json
                            example: !include image.example.json
                    responses:
                        201:
                        204:
                        400:
                        409:
            /swatch:
                put:
                    queryParameters:
                        merchantId:
                            description: Merchant Id provided by Jet
                    description: This method updates the swatch image for the specified merchant SKU
                    body:
                        application/json:
                            schema: !include image.schema.json
                            example: !include image.example.json
                    responses:
                        201:
                        204:
                        400:
                        409:
        /shippingexception:
            put:
                queryParameters:
                    merchantId:
                        description: Merchant Id provided by Jet
                description: This method updates shipping exception data for the specified merchant SKU
                body:
                    application/json:
                        schema: !include shippingexception.schema.json
                        example: !include shippingexception.example.json
                responses:
                    201:
                    204:
                    400:
                    409:
