#%RAML 0.8

title: Registration
description: The Registration API provides all methods for registering a partner account at Jet.
baseUri: https://merchant-api.jet.com/api/registration
version: v0.1
protocols: [HTTPS]
mediaType: application/json

/registration:
    /create
        post:
            description: This method will create a merchant account 
            body:
                application/json:
                    schema: !include registration-create.schema.json
                    example: !include registration-create.example.json
            responses:
                200:
                    body:
                        application/json:
                            schema: !include registration-merchantCreated.schema.json
                            exmaple: !include registration-merchantCreated.example.json
                404:
                    description: The requested resource could not be found. 
    /complete:
        /{merchant_id}
            put:
                description: This method will update merchant properties
                responses:
                    200:
                        body:
                            application/json:
                                schema: !include registration-update.schema.json
                                example: !include registration-update.example.json
                    404:
                        description: The requested resource could not be found.
    /status:
        /{merchant_id}
            get:
                description: This method will return a merchant's application status
                responses:
                    200:
                        body:
                            application/json:
                                schema: !include registration-status.schema.json
                                example: !include registration-status.example.json
                    404:
                        description: The requested resource could not be found.       