#%RAML 0.8
title: Products
description: This API provides information about all methods that affect merchant SKU set up, price, inventory, and shipping exceptions.   Explanations about the flow of information between methods in this API can be found in the API Explanations tab under the Products section.  When looking at the methods for this schema, please ignore "?subscription-key= Your subscription key" in any URLs.
baseUri: https://merchant-api.jet.com/api
version: v0.1
protocols: [HTTPS]
mediaType: application/json

/merchant-skus/?offset={offset}&limit={limit}:
    get:
        description: This method will list all merchant SKU links.  The variable {offset} refers to the starting location on the page and {limit} refers to the number of results returned.  If no {offset} or {limit} are specified, the first 1,000 SKUs are returned
        responses:
            200:
                description: List of all merchant SKUs on the page.  If not specified, 1,000 SKUs are returned
                body:
                    application/json:
                        schema: !include links.schema.json
                        example: !include links.example.json
            401:
            404:
    /bystatus/{MerchantSkuStatus}/{StartPoint}/{ResultsToReturn}:
        get:
            description: This method will list all merchant SKUs by merchantSku Status
            responses:
                200:
                    description: List of all merchant SKUs
                    body:
                        application/json:
                            schema: !include merchantSkus-returnByStatus.schema.json
                            example: !include merchantSkus-returnByStatus.example.json
                401:
                404:
    /{id}:
        get:
            description: This method will return merchant SKU specified by ID
            responses:
                200:
                    body:
                        application/json:
                            schema: !include merchantSkus-get.schema.json
                            example: !include merchantSkus-get.example.json
                401:
                404:
        put:
            description: This method will create/update the specified merchant SKU
            body:
                application/json:
                    schema: !include merchantSkus-put.schema.json
                    example: !include merchantSkus-put.example.json
            responses:
                201:
                204:
                400:
                401:
                404:
        /relationship:
            put:
                description: This method updates variation relationships between merchant SKUs
                body:
                    application/json:
                        schema: !include relationship.schema.json
                        example: !include relationship.example.json
                responses:
                    201:
                    204:
                    400:
                    401:
                    404:
        /inventory:
            get:
                description: This method retrieves fulfillment node-level inventory data for the specified merchant SKU
                responses:
                    200:
                        body:
                            application/json:
                                schema: !include merchantSkus-inventory.schema.json
                                example: !include merchantSkus-inventory.example.json
                    400:
                    401:
                    404:
            put:
                description: This method updates fulfillment node-level inventory data for the specified merchant SKU
                body:
                    application/json:
                        schema: !include merchantSkus-inventory.schema.json
                        example: !include merchantSkus-inventory.example.json
                responses:
                   201:
                   204:
                   400:
                   401:
                   404:
        /price:
            get:
                description: This method retrieves pricing data for the specified merchant SKU
                responses:
                    200:
                        body:
                        application/json:
                            schema: !include merchantSkus-price.schema.json
                            example: !include merchantSkus-price.example.json
                    400:
                    401:
                    404:
            put:
                description: This method updates price data for the specified merchant SKU
                body:
                    application/json:
                        schema: !include merchantSkus-price.schema.json
                        example: !include merchantSkus-price.example.json
                responses:
                   201:
                   204:
                   400:
                   401:
                   404:   
        /image:
            put:
                description: This method is used to provide the links to all images that should be shown to the customer for the merchant SKU
                body:
                    application/json:
                        schema: !include merchantSkus-imageBatch.schema.json
                        example: !include merchantSkus-imageBatch.example.json
                responses:
                    201:
                    204:
                    400:
                    401:
                    404:
            delete:
                    description: This method deletes any images that were provided to Jet.com
                    body:
                        application/json:
                            schema: !include merchantSkus-imageBatch.schema.json
                            example: !include merchantSkus-imageBatch.example.json
                    responses:
                        204:
                        400:
                        401:
                        404:
        /shippingexception:
            put:
                description: This method updates shipping exception data for the specified merchant SKU
                body:
                    application/json:
                        schema: !include merchantSkus-shippingException.schema.json
                        example: !include merchantSkus-shippingException.example.json
                responses:
                    201:
                    204:
                    400:
                    401:
                    404:
        /status/archive:
            put:
                description: This method archives a specified merchant SKU
                body:
                    application/json:
                        schema: !include merchantSkus-archiveStatus.schema.json
                        example: !include merchantSkus-archiveStatus.example.json
                responses:
                    201:
                    204:
                    400:
                    401:
                    404:
