#%RAML 0.8

title: Products
description: This API provides information about all methods that affect merchant SKU set up, price, inventory, and shipping exceptions.   Explanations about the flow of information between methods in this API can be found in the API Explanations tab under the Products section.
baseUri: http://merchant-api.test.jet.com/api
version: v0.1
protocols: [HTTPS]
mediaType: application/json

/merchant-skus:
    get:
        description: This method will list all merchant SKUs
        responses:
            200:
                description: List of all merchant SKUs
                body:
                    application/json:
                        schema: !include links.schema.json
                        example: !include links.example.json
            404:
    /{id}:
        get:
            description: This method will return merchant SKU specified by id
            responses:
                200:
                    body:
                        application/json:
                            schema: !include merchant-skus.schema.json
                            example: !include merchant-skus.example.json
                404:
        put:
            description: This method will create/update the specified merchant SKU
            body:
                application/json:
                    schema: !include merchant-skus.schema.json
                    example: !include merchant-skus.example.json
            responses:
                201:
                204:
                400:
                409:
        /relationship:
            put:
                description: This method updates variation relationships between merchant skus
                body:
                    application/json:
                        schema: !include relationship.schema.json
                        example: !include relationship.example.json
                responses:
                    201:
                    204:
                    400:
                    409:
        /inventory:
            /{fulfillmentNode}:
                get:
                    description: This method retrieves Fulfillment node-level inventory data for the specified merchant SKU
                    body:
                        application/json:
                            schema: !include inventory.schema.json
                            example: !include inventory.example.json
                    responses:
                        200:
                        404:
                put:
                    description: This method updates Fulfillment node-level inventory data for the specified merchant SKU
                    body:
                        application/json:
                            schema: !include inventory.schema.json
                            example: !include inventory.example.json
                    responses:
                       201:
                       204:
                       400:
                       409:
        /price:
            get:
                description: This method retrieves pricing data for the specified merchant SKU
                body:
                    application/json:
                        schema: !include price.schema.json
                        example: !include price.example.json
                responses:
                    200:
                    404:
            put:
                description: This method updates price data for the specified merchant SKU
                body:
                    application/json:
                        schema: !include price.schema.json
                        example: !include price.example.json
                responses:
                   201:
                   204:
                   400:
                   409:
            /{fulfillmentNode}:
                get:
                    description: This method retrieves Fulfillment node-level pricing data for the specified merchant SKU
                    body:
                        application/json:
                            schema: !include price.schema.json
                            example: !include price.example.json
                    responses:
                        200:
                        404:
                put:
                    description: This method updates Fulfillment node-level price data for the specified merchant SKU
                    body:
                        application/json:
                            schema: !include price.schema.json
                            example: !include price.example.json
                    responses:
                        201:
                        204:
                        400:
                        409:
                delete:
                    description: This method deletes the Fulfillment node-level price data for the specified merchant SKU
                    responses:
                        204:
                        400:
                        404:
        /image:
            put:
                description: This method is used to provide the links to all images that should be shown to the customer for the Merchant SKU
                body:
                    application/json:
                        schema: !include merchantSkus-imageBatch.schema.json
                        example: !include merchantSkus-imageBatch.example.json
                responses:
                    201:
                    204:
                    400:
                    409:
            delete:
                    description: This method deletes any images that were provided to Jet.com
                    body:
                        application/json:
                            schema: !include merchantSkus-imageBatch.schema.json
                            example: !include merchantSkus-imageBatch.example.json
                    responses:
                        204:
                        400:
                        404:
        /shippingexception:
            put:
                description: This method updates shipping exception data for the specified merchant SKU
                body:
                    application/json:
                        schema: !include shippingexception.schema.json
                        example: !include shippingexception.example.json
                responses:
                    201:
                    204:
                    400:
                    409:
