#%RAML 0.8

title: File Upload
description: This API provides all methods required to create a file upload.  These methods should be used to upload files that adher to the schema in the File Examples.  When looking at the methods for this schema, please ignore "?subscription-key= Your subscription key" in any URLs.
baseUri: https://merchant-api.test.jet.com/api/files
version: v0.1
protocols: [HTTPS]
mediaType: application/json

/uploadToken:
    get:
        description: Creates upload token which can be used to upload file to Jet.com
        responses:
            200:
                body:
                    application/json:
                        schema: !include files-token.schema.json
                        exmaple: !include files-token.exmaple.json
/uploaded:
    post:
        description: This method allows to notify Jet.com about file being uploaded
        body:
            application/json:
                schema: !include files-uploaded.schema.json
                exmaple: !include files-uploaded.exmaple.json
        responses:
            200:
                body:
                    application/json:
                        schema: !include files-status.schema.json
                        exmaple: !include files-status.exmaple.json
/{jet_file_id}:
    get:
        description: Returns details about particular file
        responses:
            200:
                body:
                    application/json:
                        schema: !include files-status.schema.json
                        exmaple: !include files-status.exmaple.json