#%RAML 0.8

title: File Examples
description: The File Examples Schema provides JSON examples for creating batch files to upload via the File Upload API. More documentation on the flow of information for the file examples in this schema is available in the API Explantions tab of this portal.
baseUri: https://merchant-api.jet.com/api/example
version: v0.1
protocols: [HTTPS]
mediaType: application/json

/File Template - MerchantSKUs:
    put:
        description: This file example shows how to upload multiple Merchant SKUs         
        body:
            application/json:
                schema: !include bulkOperations-merchantSku.schema.json
                example: !include bulkOperations-merchantSku.example.json
        responses:
            201:
            401:
            404:
/File Template - Inventory: 
    put:
        description: This file example shows how to upload inventory for multiple Merchant SKUs         
        body:
            application/json:
                schema: !include bulkOperations-inventory.schema.json
                example: !include bulkOperations-inventory.example.json
        responses:
            200:
            201:
            401:
            404:
/File Template - Price: 
    put:
        description: This file example shows how to upload price for multiple Merchant SKUs         
        body:
            application/json:
                schema: !include bulkOperations-price.schema.json
                example: !include bulkOperations-price.example.json
        responses:
            200:
            201:
            401:
            404:
/File Template - Relationship: 
    put:
        description: This file example shows how to relate multiple Merchant SKUs to each other        
        body:
            application/json:
                schema: !include bulkOperations-relationship.schema.json
                example: !include bulkOperations-relationship.example.json
        responses:
            200:
            201:
            401:
            404:
/File Template - Archive: 
    put:
        description: This file example shows how to archive multiple Merchant SKUs         
        body:
            application/json:
                schema: !include bulkOperations-archive.schema.json
                example: !include bulkOperations-archive.example.json
        responses:
            200:
            201:
            401:
            404:
/File Template - ShippingException: 
    put:
        description: This file example shows how to set shipping exceptions for multiple Merchant SKUs         
        body:
            application/json:
                schema: !include bulkOperations-shippingException.schema.json
                example: !include bulkOperations-shippingException.example.json
        responses:
            200:
            201:
            401:
            404: